version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume
  
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - 8080:8080
    networks:
      - grafana-net
  telegraf:
    image: telegraf
    container_name: telegraf
    networks:
      - grafana-net
    volumes:
      - ${PWD}/telegraf2.conf:/etc/telegraf/telegraf.conf:ro
networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true